rpc:
  endpoint: "tcp://localhost:8547"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        path: /subscriptions

rest:
  enable: true

txn:
  max-blocks-to-scan: 2000

spring.jackson.serialization.indent-output: true

