#{"query": "{ txnApi {transactions(first: 3) {to from}} }"}
transactions:
  query: "{\"query\":
              \"{
                txnApi {
                  transactions(first: 3) {
                    to
                    from
                    value
                    timestamp
                  }
                }
              }\"
        }"

blocks:
  query: "{\"query\":
                \"{
                 blockApi {
                     blocks(first: 5, before: 1496491) {
                       number
                       hash
                       parentHash
                       nrgConsumed
                       nrgLimit
                       txDetails {
                         to
                         from
                         value
                         timestamp
                       }
                     }
                 }
            }\"
        }"

rpc:
  endpoint: "tcp://localhost:8547"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        path: /subscriptions

txn:
  max-blocks-to-scan: 2000
